#!/usr/bin/env bun
/**
 * generate-zod-schemas.ts
 *
 * Reads your prisma/schema.prisma (via Prisma's DMMF) and generates a
 * schemas.ts with Zod schemas + inferred types for every model and enum.
 *
 * Naming convention (per model X) — matches what we hand-wrote:
 *   XBaseSchema   / XBaseType    — scalar fields only, no relations
 *   XSchema       / XType        — scalars + relations (z.lazy, for circular refs)
 *   XCreateSchema / XCreateType
 *   XUpdateSchema / XUpdateType
 *
 * Usage:
 *   bun add -D @prisma/internals @prisma/generator-helper
 *   bun run scripts/generate-zod-schemas.ts
 *   bun run scripts/generate-zod-schemas.ts --schema ./prisma/schema.prisma --out ./zod.ts
 *
 * Re-run this any time your schema.prisma changes — treat schemas.ts as generated,
 * not hand-edited.
 */

import { getDMMF } from "@prisma/internals";
import type { DMMF } from "@prisma/generator-helper";
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { dirname, resolve } from "path";

// ---------------------------------------------------------------------------
// CLI args
// ---------------------------------------------------------------------------

function getArg(flag: string, fallback: string): string {
  const idx = process.argv.indexOf(flag);
  if (idx === -1) return fallback;
  const value = process.argv[idx + 1];
  return value ?? fallback;
}

const SCHEMA_PATH = resolve(getArg("--schema", "prisma/schema.prisma"));
const OUT_PATH = resolve(getArg("--out", "./zod.ts"));

// ---------------------------------------------------------------------------
// Heuristics / default-value handling
// ---------------------------------------------------------------------------

function isFunctionDefault(field: DMMF.Field, fnName: string): boolean {
  const d = field.default as any;
  return !!d && typeof d === "object" && d.name === fnName;
}

/** Fields whose value the DB/Prisma generates — never ask the client for these on create. */
function isAutoGenerated(field: DMMF.Field): boolean {
  return (
    field.isId ||
    field.isUpdatedAt ||
    isFunctionDefault(field, "now") ||
    isFunctionDefault(field, "autoincrement") ||
    isFunctionDefault(field, "dbgenerated")
  );
}

/** Literal (non-function) default values we can safely echo into `.default(...)`. */
function defaultLiteral(field: DMMF.Field): string | undefined {
  const d = field.default as any;
  if (d === undefined || d === null) return undefined;
  if (typeof d === "object") return undefined; // function call e.g. now(), uuid(), cuid()
  if (typeof d === "string")
    return field.kind === "enum" ? `"${d}"` : JSON.stringify(d);
  if (typeof d === "boolean" || typeof d === "number") return String(d);
  return undefined;
}

// ---------------------------------------------------------------------------
// Scalar type -> zod mapping
// ---------------------------------------------------------------------------

function scalarZod(field: DMMF.Field): string {
  switch (field.type) {
    case "String":
      if (field.isId || isFunctionDefault(field, "uuid")) return "z.uuid()";
      if (isFunctionDefault(field, "cuid")) return "z.string().cuid()";
      if (/email/i.test(field.name)) return "z.email().toLowerCase()";
      if (/^(url|image|avatar|website)$/i.test(field.name))
        return `z.url("Must be a valid URL")`;
      return "z.string()";
    case "Int":
      return "z.number().int()";
    case "Float":
    case "Decimal":
      return "z.number()";
    case "BigInt":
      return "z.bigint()";
    case "Boolean":
      return "z.boolean()";
    case "DateTime":
      return "dateSchema";
    case "Json":
      return "z.unknown()";
    case "Bytes":
      return "z.instanceof(Uint8Array)";
    default:
      return "z.unknown()";
  }
}

function fieldToZod(field: DMMF.Field): string {
  let out = field.kind === "enum" ? `${field.type}Schema` : scalarZod(field);

  if (field.isList) out = `${out}.array()`;
  if (!field.isRequired && !field.isList) out = `${out}.nullable().optional()`;

  if (
    field.hasDefaultValue &&
    field.kind !== "object" &&
    !isAutoGenerated(field)
  ) {
    const lit = defaultLiteral(field);
    if (lit !== undefined) out = `${out}.default(${lit})`;
  }

  return out;
}

// ---------------------------------------------------------------------------
// Per-model generation
// ---------------------------------------------------------------------------

function generateModel(model: DMMF.Model): string {
  const scalarFields = model.fields.filter((f) => f.kind !== "object");
  const relationFields = model.fields.filter((f) => f.kind === "object");
  const name = model.name;
  const lines: string[] = [];

  lines.push(`/* ${"-".repeat(74)} */`);
  lines.push(`/* ${name.padEnd(74)} */`);
  lines.push(`/* ${"-".repeat(74)} */\n`);

  // 1. Base Schema
  lines.push(`// 1. Base Schema`);
  lines.push(`export const ${name}BaseSchema = z.object({`);
  for (const f of scalarFields) lines.push(`  ${f.name}: ${fieldToZod(f)},`);
  lines.push(`});\n`);

  // 2. Base Type
  lines.push(`// 2. Base Type`);
  lines.push(
    `export type ${name}BaseType = z.infer<typeof ${name}BaseSchema>;\n`,
  );

  if (relationFields.length > 0) {
    // 3. Full Type
    lines.push(
      `// 3. Full Type (interface so it can participate in circular relations)`,
    );
    lines.push(`export interface ${name}Type extends ${name}BaseType {`);
    for (const f of relationFields) {
      const t = `${f.type}Type${f.isList ? "[]" : f.isRequired ? "" : " | null"}`;
      lines.push(`  ${f.name}: ${t};`);
    }
    lines.push(`}\n`);

    // 4. Full Schema
    lines.push(`// 4. Full Schema`);
    lines.push(
      `export const ${name}Schema: z.ZodType<${name}Type> = ${name}BaseSchema.extend({`,
    );
    for (const f of relationFields) {
      let ref = `z.lazy(() => ${f.type}Schema)`;
      if (f.isList) ref = `z.lazy(() => ${f.type}Schema.array())`;
      else if (!f.isRequired) ref = `z.lazy(() => ${f.type}Schema).nullable()`;
      lines.push(`  ${f.name}: ${ref},`);
    }
    lines.push(`});\n`);
  } else {
    lines.push(`// 3. Full Type — no relations, so Full === Base`);
    lines.push(`export type ${name}Type = ${name}BaseType;\n`);
    lines.push(`// 4. Full Schema — no relations, so Full === Base`);
    lines.push(
      `export const ${name}Schema: z.ZodType<${name}Type> = ${name}BaseSchema;\n`,
    );
  }

  // 5. Create / Update
  const omitFields = scalarFields.filter(isAutoGenerated).map((f) => f.name);
  const optionalDefaultFields = scalarFields.filter(
    (f) => f.hasDefaultValue && !isAutoGenerated(f),
  );

  lines.push(`// 5. Create / Update variants`);
  const base = omitFields.length
    ? `${name}BaseSchema.omit({ ${omitFields.map((n) => `${n}: true`).join(", ")} })`
    : `${name}BaseSchema`;

  if (optionalDefaultFields.length > 0) {
    lines.push(`export const ${name}CreateSchema = ${base}.extend({`);
    for (const f of optionalDefaultFields)
      lines.push(`  ${f.name}: ${fieldToZod(f)}.optional(),`);
    lines.push(`});`);
  } else {
    lines.push(`export const ${name}CreateSchema = ${base};`);
  }
  lines.push(
    `export type ${name}CreateType = z.infer<typeof ${name}CreateSchema>;\n`,
  );

  lines.push(
    `export const ${name}UpdateSchema = ${name}CreateSchema.partial();`,
  );
  lines.push(
    `export type ${name}UpdateType = z.infer<typeof ${name}UpdateSchema>;\n`,
  );

  return lines.join("\n");
}

function generateEnum(e: DMMF.DatamodelEnum): string {
  const values = e.values.map((v) => `"${v.name}"`).join(", ");
  return [
    `export const ${e.name}Schema = z.enum([${values}]);`,
    `export type ${e.name} = z.infer<typeof ${e.name}Schema>;\n`,
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  const datamodel = readFileSync(SCHEMA_PATH, "utf-8");
  const dmmf = await getDMMF({ datamodel });

  const header = `/**
 * schemas.ts — AUTO-GENERATED. DO NOT EDIT BY HAND.
 * Source: ${SCHEMA_PATH.split("/").pop()}
 * Regenerate with: bun run generate:schemas
 *
 * Naming convention (per model X):
 *  1. XBaseSchema   / XBaseType   — scalars only, no relations
 *  2. XSchema       / XType       — scalars + relations (z.lazy for circular refs)
 *  3. XCreateSchema / XCreateType
 *  4. XUpdateSchema / XUpdateType
 */
import z from "zod";

/* ------------------------------------------------------------------------ */
/* Shared primitives                                                        */
/* ------------------------------------------------------------------------ */

const dateSchema = z.coerce.date();
`;

  const enumsCode = dmmf.datamodel.enums.map(generateEnum).join("\n");
  const modelsCode = dmmf.datamodel.models.map(generateModel).join("\n");
  const output = [header, enumsCode, modelsCode].join("\n");

  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, output, "utf-8");

  console.log(
    `✅ Generated ${dmmf.datamodel.models.length} model(s), ${dmmf.datamodel.enums.length} enum(s) → ${OUT_PATH}`,
  );
}

main().catch((err) => {
  console.error("❌ Failed to generate schemas:", err);
  process.exit(1);
});
